### PR TITLE
Kuma + NSM vl3 integration

### PR DESCRIPTION
**Pull request by ThetaDR**
Signed-off-by: Vyacheslav Tumanov <me@slavatumanov.me>

New feature: Kuma + NSM vl3 integration.

### CODE REVIEW

**Comment by ThetaDR** [comment]
We are planning to release NSM v1.6.0 next week, please do not merge before that (I'll update this PR to v1.6.0 links).

**Comment by ThetaDR** [comment]
@bartsmykla Could you please review and merge this?

**Comment by bartsmykla** [comment]
Hi @ThetaDR sure, I'm on it, apology for the elongate time, but we were very busy working on kuma 2.0

**Comment by bartsmykla** [comment]
Hi @ThetaDR, I tried to test your instructions and all was good to the step no. 6, which is failing with 
image
Could you instruct me how could I debug this issue?

**Comment by ThetaDR** [comment]
@bartsmykla Hi, it might've been due to some incorrect refs, sorry, I somehow missed them, just committed a fix. 
But also you can check via `kubectl --kubeconfig=$KUBECONFIG1 get netsvc -A` it should have my-vl3-network there

**Comment by bartsmykla** [comment]
Unfortunately I have the same problems after your update.

```shell
~/kuma-tmp > kubectl --kubeconfig=$KUBECONFIG1 get netsvc -A
# NAMESPACE    NAME             AGE
# nsm-system   my-vl3-network   3m39s
~/kuma-tmp> kubectl --kubeconfig=$KUBECONFIG2 get netsvc -A
# No resources found
```

**Comment by ThetaDR** [comment]
@bartsmykla could you please provide cluster-info dump from both clusters? I'll take a deeper look

**Comment by bartsmykla** [comment]
lgtm now

**Pull request merged**
